# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Eric Slyman
title: Computer Science // Data Science
email: slymane@wwu.edu
website: ericslyman.com

# Social links
#twitter_username: facespics
github_username: zefruis
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: ericslyman
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/portrait.jpg
about_content: | # this will include new lines to allow paragraphs
  Graduate student and deep learning researcher at Western Washington University.

  I hold the current state and rapid advancement of deep learning to be one of the most astounding features in modern applications of computer science. Specifically, I have found great draw to the rolls of DL in signal processing through performing analysis of raw images, audio, and video. Further improvements on DL have the capacity to affect the lives of a great number of people, and I hold myself to the goal of being part of such change. 

# I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# Projects Section
# projects_title: Projects

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Besdies school work and research I also have several hobbies!
   - Hiking
   - Reading sci-fy (or just Dune 20 times)
   - Producing music
   - Tracking down new IPAs

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
